# Generated by Django 3.0.5 on 2020-04-15 14:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Заголовок')),
                ('type', models.CharField(blank=True, choices=[('application', 'Application'), ('audio', 'Audio'), ('example', 'Example'), ('image', 'Image'), ('message', 'Message'), ('model', 'Model'), ('multipart', 'Multipart'), ('text', 'Text'), ('video', 'Video')], max_length=30, null=True, verbose_name='Тип контента')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('counter', models.PositiveIntegerField(blank=True, default=0, verbose_name='Cчетчик просмотров')),
                ('json_attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=66, verbose_name='MIME-тип')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Запись страницы',
                'verbose_name_plural': 'Записи страниц',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Битрейт (кбит/с, kbps)')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Content')),
                ('mime_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.MimeType')),
            ],
            options={
                'verbose_name': 'Данные (файл) контента',
                'verbose_name_plural': 'Данные (файлы) контента',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Post'),
        ),
    ]
