#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

if [ "$DATABASE" = "postgres" ]
then
    echo "Waiting for postgres..."

    while ! nc -z $SQL_HOST $SQL_PORT; do
      sleep 0.1
    done

    echo "PostgreSQL started"
fi

pipenv run python manage.py makemigrations
pipenv run python manage.py migrate
pipenv run python manage.py loaddata fixtures/mimetypes_data.json
pipenv run python manage.py loaddata fixtures/dev_users.json
pipenv run python manage.py runserver 0.0.0.0:8000

exec "$@"